In [12]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import SimpleRNN, Embedding, Dense

In [59]:
# Sample Text Data
text = 'I love deep learning'
chars = sorted(list(set(text)))
char_to_index = {c: i for i, c in enumerate(chars)}
index_to_char = {i: c for i, c in enumerate(chars)}

In [53]:
# Convert text to integer sequence
seq = [char_to_index[c] for c in text]
seq

[1, 0, 7, 9, 12, 4, 0, 3, 4, 4, 10, 0, 7, 4, 2, 11, 8, 6, 8, 5]

In [54]:
# Prepare training data (input-output pairs)
X = []
y = []
seq_length = 3
for i in range(len(seq) - seq_length):
  X.append(seq[i:i+seq_length])
  y.append(seq[i+seq_length])
X = np.array(X)
y = np.array(y)
X, y

(array([[ 1,  0,  7],
        [ 0,  7,  9],
        [ 7,  9, 12],
        [ 9, 12,  4],
        [12,  4,  0],
        [ 4,  0,  3],
        [ 0,  3,  4],
        [ 3,  4,  4],
        [ 4,  4, 10],
        [ 4, 10,  0],
        [10,  0,  7],
        [ 0,  7,  4],
        [ 7,  4,  2],
        [ 4,  2, 11],
        [ 2, 11,  8],
        [11,  8,  6],
        [ 8,  6,  8]]),
 array([ 9, 12,  4,  0,  3,  4,  4, 10,  0,  7,  4,  2, 11,  8,  6,  8,  5]))

In [36]:
y = np.array([word_embeddings[word] for word in text.split()[1:]])
y

array([2., 3., 4.])

In [55]:
# Build RNN Model
model = Sequential([
    Embedding(input_dim=len(chars), output_dim=10, input_length=seq_length),
    SimpleRNN(20, activation='tanh'),
    Dense(len(chars), activation='softmax')
])

model.compile(loss='sparse_categorical_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])
model.summary()

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


Model: "sequential_6"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn_6 (SimpleRNN)        │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_6 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [56]:
# Train Model
model.fit(X, y, epochs=200, verbose=0)

In [69]:
# Test prediction
test_seq = X[0]
pred = model.predict(np.array([test_seq]))
pred_char = index_to_char[np.argmax(pred)]
print("Input:", ''.join([index_to_char[i] for i in test_seq]))
print("Predicted next char:", pred_char)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step
Input: I l
Predicted next char: o


In [70]:
model.evaluate(X, y)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 340ms/step - accuracy: 1.0000 - loss: 0.3145


[0.31451642513275146, 1.0]